name: json_model
description: Gernerating Dart model class from Json file.
version: 0.0.2
author: wendux <824783146@qq.com>
homepage: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.5.1
  build: ">=1.0.0 <1.2.2"
  glob: ^1.1.0
  logging: ^0.11.2
  io: ^0.3.0
  build_resolvers: ^1.3.7
  build_runner_core: ^5.1.0
  build_runner: ^1.9.0
  json_annotation: ^3.0.1
  json_serializable: ^3.3.0
  path: ^1.6.2
dev_dependencies:
  test: ^1.5.1
